name: Rust

on: [push]

env:
  RUSTFLAGS: "-D warnings"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --features=CI --no-fail-fast
